name: Bot Scan

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run-bot:
          - name: Commit data
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"
          git add data.json
          git commit -m "update data" || echo "no changes"
          git push
